FROM node:16

WORKDIR /app

RUN apt-get update && apt-get install -y postgresql-client

COPY package*.json ./
RUN npm install 

COPY prisma ./prisma/
COPY . .

RUN npx prisma generate

COPY start_waiting.sh ./start_waiting.sh
RUN chmod +x start_waiting.sh

EXPOSE 3000

COPY start.sh /app/start.sh
RUN chmod +x /app/start.sh
ENTRYPOINT ["./start_waiting.sh", "db", "--", "/app/start.sh"]